import{a as b,S,i as c}from"./assets/vendor-Sa4a0LJu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();async function f(o,t=1,l=15){try{return(await b.get("https://pixabay.com/api/",{params:{key:"49403808-1d10fbc3a3e3dae24bc03a037",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:l}})).data}catch(n){console.log(n)}}const p=document.querySelector(".gallery");let w=new S(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:l,largeImageURL:n,tags:e,likes:r,views:i,comments:g,downloads:h})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${l}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p>Likes: ${r}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${g}</p>
            <p>Downloads: ${h}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",t),w.refresh()}function L(){p.innerHTML=""}const a={form:document.querySelector(".form"),input:document.querySelector('[name="search-text"]'),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};let d="",s=1;const u=15;let y=0;a.form.addEventListener("submit",q);a.loadMoreBtn.addEventListener("click",v);async function q(o){if(o.preventDefault(),d=a.input.value.trim(),!d){c.error({message:"Please enter a search query!"});return}s=1,L(),a.loadMoreBtn.style.display="none";try{a.loader.style.display="block";const t=await f(d,s,u);if(y=t.totalHits,t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}m(t.hits),s*u<y&&(a.loadMoreBtn.style.display="block")}catch{c.error({message:"Something went wrong. Try again later!"})}finally{a.loader.style.display="none"}}async function v(){s++;try{a.loader.style.display="block";const o=await f(d,s,u);m(o.hits),M(),s*u>=y&&(a.loadMoreBtn.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Something went wrong. Try again later!"})}finally{a.loader.style.display="none"}}function M(){const{height:o}=a.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
